export const API_ROUTES = {
  AUTH: {
    REGISTER: '/users/auth/register/',
    VERIFY_OTP: '/users/auth/verify-otp/',
    RESEND_VERIFY_PHONE: '/users/auth/resend-verify-phone/',
    LOGIN_WITH_PASSWORD: '/users/login/login-with-password/',
    EMAIL_LOGIN: '/users/login/email-login/',
    PHONE_LOGIN: '/users/login/phone-login/',
    VERIFY_OTP_LOGIN: '/users/login/verify-otp-login/',
    RESEND_OTP: '/users/login/resend-otp/',
    FORGOT_PASSWORD_EMAIL: '/users/forgot-password/send-reset-link/',
    FORGOT_PASSWORD_SEND_OTP: '/users/forgot-password/send-otp/',
    FORGOT_PASSWORD_VERIFY_OTP: '/users/forgot-password/verify-otp/',
    FORGOT_PASSWORD_RESEND_OTP: '/users/forgot-password/resend-otp/',
    FORGOT_PASSWORD_RESET_PASSWORD_SMS:
      '/users/forgot-password/reset-password-sms/',
    REFRESH_TOKEN: '/users/token/refresh/',
    USER_VIEW: '/users/user-view/',
    USER_UPDATE: '/users/user-view/',
  },
  CONFIG: {
    COUNTRY_LANGUAGE_OPTIONS: '/users/country-language-options/',
  },
  PRODUCTS: {
    HOME: '/products/home/v1/',
    DETAIL: '/products/product-detail/',
    CATEGORIES: '/products/category/',
    CATEGORY_SUBCATEGORIES: (slug: string) => `/products/category/${slug}`,
    FILTER_VIEW: '/products/filter-view/',
    SEARCH_SUGGESTIONS: '/products/search/',
    SEARCH_RESULTS: '/products/search/results/',
    LISTING: '/products/listing/',
    VIEW_ALL: '/products/view-all',
    FABRIC_CONFIG: (slug: string) => `/products/${slug}/fabric-config/`,
    TRY_IN_STORE: (slug: string) => `/products/${slug}/try-in-store/`,
  },
  WISHLIST: {
    COLLECTIONS: '/wishlist/wishlist/',
    CREATE_COLLECTION: '/wishlist/wishlist/create-collection/',
    ADD_ITEM: '/wishlist/wishlist/add-item/',
    REMOVE_VARIANT: (variantId: number) =>
      `/wishlist/wishlist/remove-variant/${variantId}/`,
  },
  CART: {
    DETAIL: '/cart/',
    ADD_ITEM: '/cart/items/',
    REMOVE_ITEM: (cartId: string) => `/cart/${cartId}/items/`,
    UPDATE_ITEM: (cartId: string) => `/cart/${cartId}/update/`,
    SAVE_FOR_LATER: (cartItemId: string) => `/cart/${cartItemId}/save/`,
    MOVE_TO_CART: (cartItemId: string) => `/cart/${cartItemId}/move/`,
    SHIPPING_PROCEED: '/cart/shipping/proceed/',
    PAYMENT_PROCEED: '/cart/payments/proceed/',
  },
  PAYMENT: {
    PROMOCODES: '/payment/promocodes/',
    APPLY_PROMOCODE: '/payment/promocodes/apply/',
  },
  STORES: {
    BY_CART: '/store/by-cart/',
  },
  USERS: {
    LOCATION: '/users/location/',
    EMIRATE_LIST: '/users/emirate-list/',
    OTP_SEND: '/users/otp/send/',
    OTP_VERIFY: '/users/otp/verify/',
  },
  ADDRESSES: {
    ROOT: '/users/addresses/',
    DETAIL: (id: number | string) => `/users/addresses/${id}/`,
  },
  ORDERS: {
    LIST: '/order/',
    DETAIL: (id: string) => `/order/detail/${id}/`,
    TRACKING: (id: string) => `/order/tracking/${id}/`,
    CANCEL: '/order/cancel/',
    REFUND_REQUEST: '/order/refund/request/',
    DELIVERY_SLOTS: '/order/delivery/slots/',
    DELIVERY_PREFERENCES: '/order/delivery/preferences/',
    CHECKOUT: '/order/checkout/',
  },
} as const;
