import { configService } from '@/services/api/config-service';
import fs from 'fs';
import path from 'path';

async function run() {
  console.log('Running pre-run script...');
  try {
    const response = await configService.getCountryLanguageOptions();
    const data = response.data;

    console.log('--- Country & Language Options Fetched ---');

    // Ensure the generated directory exists
    const dir = path.join(process.cwd(), 'src', 'generated');
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const filePath = path.join(dir, 'countries.ts');

    const fileContent = `// This file is auto-generated by scripts/pre-run.ts
// Do not edit this file manually.

export const countries = ${JSON.stringify(data, null, 2)} as const;

export type Country = (typeof countries)[number];
`;

    fs.writeFileSync(filePath, fileContent);
    console.log(`Successfully generated ${filePath}`);
    console.log('---------------------------------');
    console.log('Pre-run script executed successfully!');
  } catch (error) {
    console.error(
      'Failed to fetch country language options or write file:',
      error
    );
    process.exit(1);
  }
}

run();
